/* This file is generated by scripts/sync-shop-homepage.mjs. */

import type { SyncedShopHomepage } from "./homepage";

export const leatherWorshipHomepage = {
  sourceUrl: "https://leatherworship.com/",
  modules: [
    {
      id: "fw-section-featured-collection-88141a66-3ba0-490d-9aa8-0329972bc912",
      type: "collection",
      title: "Impact toys",
      productSlugs: [
        "spike-spanker-princess",
        "spike-spanker-heart",
        "spike-spanker-sadist",
        "spike-impact-smacker-and-stim-toy",
        "spike-thigh-wrap-pain-stim-toy",
        "thigh-wrap-heart",
        "sadist-spike-thigh-wrap-pain-stim-toy",
        "classic-star-spike-thigh-wrap-pain-stim-toy",
      ],
    },
    {
      id: "fw-section-featured-product-30b9afa4-fbc5-4e6a-b697-0533dd95ca6b",
      type: "product",
      productSlug: "puppy-paw-spike-toy",
    },
    {
      id: "fw-section-featured-collection-52c160a2-858f-483a-affd-1d6bbcbe6a3d",
      type: "collection",
      title: "Uniforms for the devoted.",
      productSlugs: [
        "garbage-baby-tee",
        "dont-bully-me-ill-bark-baby-tee",
        "obey-kneel-submit-relax-bdsm-crop-t-shirt",
        "negotiate-play-aftercare-repeat-bdsm-t-shirt",
      ],
    },
    {
      id: "fw-section-featured-collection-0",
      type: "collection",
      title: "Signature pieces",
      productSlugs: [
        "the-crimson-testament-signature-collar",
        "the-eden-signature-collar",
        "the-iron-testament-signature-collar",
        "the-emerald-seal-signature-collar",
      ],
    },
    {
      id: "fw-section-featured-collection-e02a79e1-207b-44fe-8979-351a89f904f3",
      type: "collection",
      title: "Pup play collars",
      productSlugs: [
        "lil-pup-collar",
        "frisky-dog-collar",
        "big-dog-choker-and-leash-convertible",
        "troublemaker-pup-collar",
      ],
    },
    {
      id: "fw-section-featured-collection-810dcf94-8fa9-4e47-99d8-e4da91dc2cd3",
      type: "collection",
      title: "BDSM gear and accessories",
      productSlugs: [
        "copy-of-spike-spanker-classic",
        "dominion-bondage-belt",
        "leather-flogger-bag-charm",
        "everyday-leather-leash-black-natural",
      ],
    },
    {
      id: "fw-section-image-with-text-00ab18ea-9b98-4177-bbfe-9906711c2108",
      type: "commission",
    },
  ],
} satisfies SyncedShopHomepage;
