/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZinesRouteImport } from './routes/zines'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SceneNegotiatorRouteImport } from './routes/scene-negotiator'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlayPartyNegotiationFormRouteImport } from './routes/play-party-negotiation-form'
import { Route as PlayPartyNegotiationChecklistRouteImport } from './routes/play-party-negotiation-checklist'
import { Route as NegotiateRouteImport } from './routes/negotiate'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZinesIndexRouteImport } from './routes/zines.index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as SceneNegotiatorIndexRouteImport } from './routes/scene-negotiator.index'
import { Route as ZinesZineSlugRouteImport } from './routes/zines.$zineSlug'
import { Route as ShopTermsOfServiceRouteImport } from './routes/shop.terms-of-service'
import { Route as ShopReturnsFaqRouteImport } from './routes/shop.returns-faq'
import { Route as ShopPrivacyPolicyRouteImport } from './routes/shop.privacy-policy'
import { Route as ServicesPolyamoryCoachingForBeginnersRouteImport } from './routes/services.polyamory-coaching-for-beginners'
import { Route as ServicesKinkEventAccompanimentRouteImport } from './routes/services.kink-event-accompaniment'
import { Route as ServicesKinkCoachSanFranciscoRouteImport } from './routes/services.kink-coach-san-francisco'
import { Route as ServicesBeginnerBdsmCoachingRouteImport } from './routes/services.beginner-bdsm-coaching'
import { Route as SceneNegotiatorSettingsRouteImport } from './routes/scene-negotiator.settings'
import { Route as SceneNegotiatorOnboardingRouteImport } from './routes/scene-negotiator.onboarding'
import { Route as SceneNegotiatorKinksRouteImport } from './routes/scene-negotiator.kinks'
import { Route as GuidesPreparingForYourFirstKinkEventRouteImport } from './routes/guides.preparing-for-your-first-kink-event'
import { Route as GuidesKinkRedFlagsForBeginnersRouteImport } from './routes/guides.kink-red-flags-for-beginners'
import { Route as GuidesHowToNegotiateYourFirstSceneRouteImport } from './routes/guides.how-to-negotiate-your-first-scene'
import { Route as GuidesHowToEnterTheKinkSceneRouteImport } from './routes/guides.how-to-enter-the-kink-scene'
import { Route as SceneNegotiatorSessionsIndexRouteImport } from './routes/scene-negotiator.sessions.index'
import { Route as ShopProductsProductSlugRouteImport } from './routes/shop.products.$productSlug'
import { Route as ShopCollectionsCollectionSlugRouteImport } from './routes/shop.collections.$collectionSlug'
import { Route as SceneNegotiatorSessionsNewRouteImport } from './routes/scene-negotiator.sessions.new'
import { Route as SceneNegotiatorSceneTokenRouteImport } from './routes/scene-negotiator.scene.$token'
import { Route as SceneNegotiatorJoinTokenRouteImport } from './routes/scene-negotiator.join.$token'
import { Route as SceneNegotiatorSessionsSessionIdIndexRouteImport } from './routes/scene-negotiator.sessions.$sessionId.index'
import { Route as SceneNegotiatorSessionsSessionIdSceneRouteImport } from './routes/scene-negotiator.sessions.$sessionId.scene'
import { Route as SceneNegotiatorSessionsSessionIdEditRouteImport } from './routes/scene-negotiator.sessions.$sessionId.edit'
import { Route as SceneNegotiatorSessionsSessionIdAftercareRouteImport } from './routes/scene-negotiator.sessions.$sessionId.aftercare'

const ZinesRoute = ZinesRouteImport.update({
  id: '/zines',
  path: '/zines',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneNegotiatorRoute = SceneNegotiatorRouteImport.update({
  id: '/scene-negotiator',
  path: '/scene-negotiator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPartyNegotiationFormRoute =
  PlayPartyNegotiationFormRouteImport.update({
    id: '/play-party-negotiation-form',
    path: '/play-party-negotiation-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlayPartyNegotiationChecklistRoute =
  PlayPartyNegotiationChecklistRouteImport.update({
    id: '/play-party-negotiation-checklist',
    path: '/play-party-negotiation-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const NegotiateRoute = NegotiateRouteImport.update({
  id: '/negotiate',
  path: '/negotiate',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZinesIndexRoute = ZinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZinesRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const SceneNegotiatorIndexRoute = SceneNegotiatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SceneNegotiatorRoute,
} as any)
const ZinesZineSlugRoute = ZinesZineSlugRouteImport.update({
  id: '/$zineSlug',
  path: '/$zineSlug',
  getParentRoute: () => ZinesRoute,
} as any)
const ShopTermsOfServiceRoute = ShopTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => ShopRoute,
} as any)
const ShopReturnsFaqRoute = ShopReturnsFaqRouteImport.update({
  id: '/returns-faq',
  path: '/returns-faq',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPrivacyPolicyRoute = ShopPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => ShopRoute,
} as any)
const ServicesPolyamoryCoachingForBeginnersRoute =
  ServicesPolyamoryCoachingForBeginnersRouteImport.update({
    id: '/services/polyamory-coaching-for-beginners',
    path: '/services/polyamory-coaching-for-beginners',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesKinkEventAccompanimentRoute =
  ServicesKinkEventAccompanimentRouteImport.update({
    id: '/services/kink-event-accompaniment',
    path: '/services/kink-event-accompaniment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesKinkCoachSanFranciscoRoute =
  ServicesKinkCoachSanFranciscoRouteImport.update({
    id: '/services/kink-coach-san-francisco',
    path: '/services/kink-coach-san-francisco',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBeginnerBdsmCoachingRoute =
  ServicesBeginnerBdsmCoachingRouteImport.update({
    id: '/services/beginner-bdsm-coaching',
    path: '/services/beginner-bdsm-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const SceneNegotiatorSettingsRoute = SceneNegotiatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SceneNegotiatorRoute,
} as any)
const SceneNegotiatorOnboardingRoute =
  SceneNegotiatorOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)
const SceneNegotiatorKinksRoute = SceneNegotiatorKinksRouteImport.update({
  id: '/kinks',
  path: '/kinks',
  getParentRoute: () => SceneNegotiatorRoute,
} as any)
const GuidesPreparingForYourFirstKinkEventRoute =
  GuidesPreparingForYourFirstKinkEventRouteImport.update({
    id: '/guides/preparing-for-your-first-kink-event',
    path: '/guides/preparing-for-your-first-kink-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesKinkRedFlagsForBeginnersRoute =
  GuidesKinkRedFlagsForBeginnersRouteImport.update({
    id: '/guides/kink-red-flags-for-beginners',
    path: '/guides/kink-red-flags-for-beginners',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHowToNegotiateYourFirstSceneRoute =
  GuidesHowToNegotiateYourFirstSceneRouteImport.update({
    id: '/guides/how-to-negotiate-your-first-scene',
    path: '/guides/how-to-negotiate-your-first-scene',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHowToEnterTheKinkSceneRoute =
  GuidesHowToEnterTheKinkSceneRouteImport.update({
    id: '/guides/how-to-enter-the-kink-scene',
    path: '/guides/how-to-enter-the-kink-scene',
    getParentRoute: () => rootRouteImport,
  } as any)
const SceneNegotiatorSessionsIndexRoute =
  SceneNegotiatorSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)
const ShopProductsProductSlugRoute = ShopProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCollectionsCollectionSlugRoute =
  ShopCollectionsCollectionSlugRouteImport.update({
    id: '/collections/$collectionSlug',
    path: '/collections/$collectionSlug',
    getParentRoute: () => ShopRoute,
  } as any)
const SceneNegotiatorSessionsNewRoute =
  SceneNegotiatorSessionsNewRouteImport.update({
    id: '/sessions/new',
    path: '/sessions/new',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)
const SceneNegotiatorSceneTokenRoute =
  SceneNegotiatorSceneTokenRouteImport.update({
    id: '/scene/$token',
    path: '/scene/$token',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)
const SceneNegotiatorJoinTokenRoute =
  SceneNegotiatorJoinTokenRouteImport.update({
    id: '/join/$token',
    path: '/join/$token',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)
const SceneNegotiatorSessionsSessionIdIndexRoute =
  SceneNegotiatorSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)
const SceneNegotiatorSessionsSessionIdSceneRoute =
  SceneNegotiatorSessionsSessionIdSceneRouteImport.update({
    id: '/sessions/$sessionId/scene',
    path: '/sessions/$sessionId/scene',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)
const SceneNegotiatorSessionsSessionIdEditRoute =
  SceneNegotiatorSessionsSessionIdEditRouteImport.update({
    id: '/sessions/$sessionId/edit',
    path: '/sessions/$sessionId/edit',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)
const SceneNegotiatorSessionsSessionIdAftercareRoute =
  SceneNegotiatorSessionsSessionIdAftercareRouteImport.update({
    id: '/sessions/$sessionId/aftercare',
    path: '/sessions/$sessionId/aftercare',
    getParentRoute: () => SceneNegotiatorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/coaching': typeof CoachingRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/negotiate': typeof NegotiateRoute
  '/play-party-negotiation-checklist': typeof PlayPartyNegotiationChecklistRoute
  '/play-party-negotiation-form': typeof PlayPartyNegotiationFormRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/scene-negotiator': typeof SceneNegotiatorRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/zines': typeof ZinesRouteWithChildren
  '/guides/how-to-enter-the-kink-scene': typeof GuidesHowToEnterTheKinkSceneRoute
  '/guides/how-to-negotiate-your-first-scene': typeof GuidesHowToNegotiateYourFirstSceneRoute
  '/guides/kink-red-flags-for-beginners': typeof GuidesKinkRedFlagsForBeginnersRoute
  '/guides/preparing-for-your-first-kink-event': typeof GuidesPreparingForYourFirstKinkEventRoute
  '/scene-negotiator/kinks': typeof SceneNegotiatorKinksRoute
  '/scene-negotiator/onboarding': typeof SceneNegotiatorOnboardingRoute
  '/scene-negotiator/settings': typeof SceneNegotiatorSettingsRoute
  '/services/beginner-bdsm-coaching': typeof ServicesBeginnerBdsmCoachingRoute
  '/services/kink-coach-san-francisco': typeof ServicesKinkCoachSanFranciscoRoute
  '/services/kink-event-accompaniment': typeof ServicesKinkEventAccompanimentRoute
  '/services/polyamory-coaching-for-beginners': typeof ServicesPolyamoryCoachingForBeginnersRoute
  '/shop/privacy-policy': typeof ShopPrivacyPolicyRoute
  '/shop/returns-faq': typeof ShopReturnsFaqRoute
  '/shop/terms-of-service': typeof ShopTermsOfServiceRoute
  '/zines/$zineSlug': typeof ZinesZineSlugRoute
  '/scene-negotiator/': typeof SceneNegotiatorIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/zines/': typeof ZinesIndexRoute
  '/scene-negotiator/join/$token': typeof SceneNegotiatorJoinTokenRoute
  '/scene-negotiator/scene/$token': typeof SceneNegotiatorSceneTokenRoute
  '/scene-negotiator/sessions/new': typeof SceneNegotiatorSessionsNewRoute
  '/shop/collections/$collectionSlug': typeof ShopCollectionsCollectionSlugRoute
  '/shop/products/$productSlug': typeof ShopProductsProductSlugRoute
  '/scene-negotiator/sessions/': typeof SceneNegotiatorSessionsIndexRoute
  '/scene-negotiator/sessions/$sessionId/aftercare': typeof SceneNegotiatorSessionsSessionIdAftercareRoute
  '/scene-negotiator/sessions/$sessionId/edit': typeof SceneNegotiatorSessionsSessionIdEditRoute
  '/scene-negotiator/sessions/$sessionId/scene': typeof SceneNegotiatorSessionsSessionIdSceneRoute
  '/scene-negotiator/sessions/$sessionId/': typeof SceneNegotiatorSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/coaching': typeof CoachingRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/negotiate': typeof NegotiateRoute
  '/play-party-negotiation-checklist': typeof PlayPartyNegotiationChecklistRoute
  '/play-party-negotiation-form': typeof PlayPartyNegotiationFormRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/guides/how-to-enter-the-kink-scene': typeof GuidesHowToEnterTheKinkSceneRoute
  '/guides/how-to-negotiate-your-first-scene': typeof GuidesHowToNegotiateYourFirstSceneRoute
  '/guides/kink-red-flags-for-beginners': typeof GuidesKinkRedFlagsForBeginnersRoute
  '/guides/preparing-for-your-first-kink-event': typeof GuidesPreparingForYourFirstKinkEventRoute
  '/scene-negotiator/kinks': typeof SceneNegotiatorKinksRoute
  '/scene-negotiator/onboarding': typeof SceneNegotiatorOnboardingRoute
  '/scene-negotiator/settings': typeof SceneNegotiatorSettingsRoute
  '/services/beginner-bdsm-coaching': typeof ServicesBeginnerBdsmCoachingRoute
  '/services/kink-coach-san-francisco': typeof ServicesKinkCoachSanFranciscoRoute
  '/services/kink-event-accompaniment': typeof ServicesKinkEventAccompanimentRoute
  '/services/polyamory-coaching-for-beginners': typeof ServicesPolyamoryCoachingForBeginnersRoute
  '/shop/privacy-policy': typeof ShopPrivacyPolicyRoute
  '/shop/returns-faq': typeof ShopReturnsFaqRoute
  '/shop/terms-of-service': typeof ShopTermsOfServiceRoute
  '/zines/$zineSlug': typeof ZinesZineSlugRoute
  '/scene-negotiator': typeof SceneNegotiatorIndexRoute
  '/shop': typeof ShopIndexRoute
  '/zines': typeof ZinesIndexRoute
  '/scene-negotiator/join/$token': typeof SceneNegotiatorJoinTokenRoute
  '/scene-negotiator/scene/$token': typeof SceneNegotiatorSceneTokenRoute
  '/scene-negotiator/sessions/new': typeof SceneNegotiatorSessionsNewRoute
  '/shop/collections/$collectionSlug': typeof ShopCollectionsCollectionSlugRoute
  '/shop/products/$productSlug': typeof ShopProductsProductSlugRoute
  '/scene-negotiator/sessions': typeof SceneNegotiatorSessionsIndexRoute
  '/scene-negotiator/sessions/$sessionId/aftercare': typeof SceneNegotiatorSessionsSessionIdAftercareRoute
  '/scene-negotiator/sessions/$sessionId/edit': typeof SceneNegotiatorSessionsSessionIdEditRoute
  '/scene-negotiator/sessions/$sessionId/scene': typeof SceneNegotiatorSessionsSessionIdSceneRoute
  '/scene-negotiator/sessions/$sessionId': typeof SceneNegotiatorSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/coaching': typeof CoachingRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/negotiate': typeof NegotiateRoute
  '/play-party-negotiation-checklist': typeof PlayPartyNegotiationChecklistRoute
  '/play-party-negotiation-form': typeof PlayPartyNegotiationFormRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/scene-negotiator': typeof SceneNegotiatorRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/zines': typeof ZinesRouteWithChildren
  '/guides/how-to-enter-the-kink-scene': typeof GuidesHowToEnterTheKinkSceneRoute
  '/guides/how-to-negotiate-your-first-scene': typeof GuidesHowToNegotiateYourFirstSceneRoute
  '/guides/kink-red-flags-for-beginners': typeof GuidesKinkRedFlagsForBeginnersRoute
  '/guides/preparing-for-your-first-kink-event': typeof GuidesPreparingForYourFirstKinkEventRoute
  '/scene-negotiator/kinks': typeof SceneNegotiatorKinksRoute
  '/scene-negotiator/onboarding': typeof SceneNegotiatorOnboardingRoute
  '/scene-negotiator/settings': typeof SceneNegotiatorSettingsRoute
  '/services/beginner-bdsm-coaching': typeof ServicesBeginnerBdsmCoachingRoute
  '/services/kink-coach-san-francisco': typeof ServicesKinkCoachSanFranciscoRoute
  '/services/kink-event-accompaniment': typeof ServicesKinkEventAccompanimentRoute
  '/services/polyamory-coaching-for-beginners': typeof ServicesPolyamoryCoachingForBeginnersRoute
  '/shop/privacy-policy': typeof ShopPrivacyPolicyRoute
  '/shop/returns-faq': typeof ShopReturnsFaqRoute
  '/shop/terms-of-service': typeof ShopTermsOfServiceRoute
  '/zines/$zineSlug': typeof ZinesZineSlugRoute
  '/scene-negotiator/': typeof SceneNegotiatorIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/zines/': typeof ZinesIndexRoute
  '/scene-negotiator/join/$token': typeof SceneNegotiatorJoinTokenRoute
  '/scene-negotiator/scene/$token': typeof SceneNegotiatorSceneTokenRoute
  '/scene-negotiator/sessions/new': typeof SceneNegotiatorSessionsNewRoute
  '/shop/collections/$collectionSlug': typeof ShopCollectionsCollectionSlugRoute
  '/shop/products/$productSlug': typeof ShopProductsProductSlugRoute
  '/scene-negotiator/sessions/': typeof SceneNegotiatorSessionsIndexRoute
  '/scene-negotiator/sessions/$sessionId/aftercare': typeof SceneNegotiatorSessionsSessionIdAftercareRoute
  '/scene-negotiator/sessions/$sessionId/edit': typeof SceneNegotiatorSessionsSessionIdEditRoute
  '/scene-negotiator/sessions/$sessionId/scene': typeof SceneNegotiatorSessionsSessionIdSceneRoute
  '/scene-negotiator/sessions/$sessionId/': typeof SceneNegotiatorSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/coaching'
    | '/disclaimer'
    | '/faq'
    | '/negotiate'
    | '/play-party-negotiation-checklist'
    | '/play-party-negotiation-form'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/scene-negotiator'
    | '/shop'
    | '/terms'
    | '/workshops'
    | '/zines'
    | '/guides/how-to-enter-the-kink-scene'
    | '/guides/how-to-negotiate-your-first-scene'
    | '/guides/kink-red-flags-for-beginners'
    | '/guides/preparing-for-your-first-kink-event'
    | '/scene-negotiator/kinks'
    | '/scene-negotiator/onboarding'
    | '/scene-negotiator/settings'
    | '/services/beginner-bdsm-coaching'
    | '/services/kink-coach-san-francisco'
    | '/services/kink-event-accompaniment'
    | '/services/polyamory-coaching-for-beginners'
    | '/shop/privacy-policy'
    | '/shop/returns-faq'
    | '/shop/terms-of-service'
    | '/zines/$zineSlug'
    | '/scene-negotiator/'
    | '/shop/'
    | '/zines/'
    | '/scene-negotiator/join/$token'
    | '/scene-negotiator/scene/$token'
    | '/scene-negotiator/sessions/new'
    | '/shop/collections/$collectionSlug'
    | '/shop/products/$productSlug'
    | '/scene-negotiator/sessions/'
    | '/scene-negotiator/sessions/$sessionId/aftercare'
    | '/scene-negotiator/sessions/$sessionId/edit'
    | '/scene-negotiator/sessions/$sessionId/scene'
    | '/scene-negotiator/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/coaching'
    | '/disclaimer'
    | '/faq'
    | '/negotiate'
    | '/play-party-negotiation-checklist'
    | '/play-party-negotiation-form'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/workshops'
    | '/guides/how-to-enter-the-kink-scene'
    | '/guides/how-to-negotiate-your-first-scene'
    | '/guides/kink-red-flags-for-beginners'
    | '/guides/preparing-for-your-first-kink-event'
    | '/scene-negotiator/kinks'
    | '/scene-negotiator/onboarding'
    | '/scene-negotiator/settings'
    | '/services/beginner-bdsm-coaching'
    | '/services/kink-coach-san-francisco'
    | '/services/kink-event-accompaniment'
    | '/services/polyamory-coaching-for-beginners'
    | '/shop/privacy-policy'
    | '/shop/returns-faq'
    | '/shop/terms-of-service'
    | '/zines/$zineSlug'
    | '/scene-negotiator'
    | '/shop'
    | '/zines'
    | '/scene-negotiator/join/$token'
    | '/scene-negotiator/scene/$token'
    | '/scene-negotiator/sessions/new'
    | '/shop/collections/$collectionSlug'
    | '/shop/products/$productSlug'
    | '/scene-negotiator/sessions'
    | '/scene-negotiator/sessions/$sessionId/aftercare'
    | '/scene-negotiator/sessions/$sessionId/edit'
    | '/scene-negotiator/sessions/$sessionId/scene'
    | '/scene-negotiator/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/coaching'
    | '/disclaimer'
    | '/faq'
    | '/negotiate'
    | '/play-party-negotiation-checklist'
    | '/play-party-negotiation-form'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/scene-negotiator'
    | '/shop'
    | '/terms'
    | '/workshops'
    | '/zines'
    | '/guides/how-to-enter-the-kink-scene'
    | '/guides/how-to-negotiate-your-first-scene'
    | '/guides/kink-red-flags-for-beginners'
    | '/guides/preparing-for-your-first-kink-event'
    | '/scene-negotiator/kinks'
    | '/scene-negotiator/onboarding'
    | '/scene-negotiator/settings'
    | '/services/beginner-bdsm-coaching'
    | '/services/kink-coach-san-francisco'
    | '/services/kink-event-accompaniment'
    | '/services/polyamory-coaching-for-beginners'
    | '/shop/privacy-policy'
    | '/shop/returns-faq'
    | '/shop/terms-of-service'
    | '/zines/$zineSlug'
    | '/scene-negotiator/'
    | '/shop/'
    | '/zines/'
    | '/scene-negotiator/join/$token'
    | '/scene-negotiator/scene/$token'
    | '/scene-negotiator/sessions/new'
    | '/shop/collections/$collectionSlug'
    | '/shop/products/$productSlug'
    | '/scene-negotiator/sessions/'
    | '/scene-negotiator/sessions/$sessionId/aftercare'
    | '/scene-negotiator/sessions/$sessionId/edit'
    | '/scene-negotiator/sessions/$sessionId/scene'
    | '/scene-negotiator/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  CoachingRoute: typeof CoachingRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  NegotiateRoute: typeof NegotiateRoute
  PlayPartyNegotiationChecklistRoute: typeof PlayPartyNegotiationChecklistRoute
  PlayPartyNegotiationFormRoute: typeof PlayPartyNegotiationFormRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SceneNegotiatorRoute: typeof SceneNegotiatorRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  TermsRoute: typeof TermsRoute
  WorkshopsRoute: typeof WorkshopsRoute
  ZinesRoute: typeof ZinesRouteWithChildren
  GuidesHowToEnterTheKinkSceneRoute: typeof GuidesHowToEnterTheKinkSceneRoute
  GuidesHowToNegotiateYourFirstSceneRoute: typeof GuidesHowToNegotiateYourFirstSceneRoute
  GuidesKinkRedFlagsForBeginnersRoute: typeof GuidesKinkRedFlagsForBeginnersRoute
  GuidesPreparingForYourFirstKinkEventRoute: typeof GuidesPreparingForYourFirstKinkEventRoute
  ServicesBeginnerBdsmCoachingRoute: typeof ServicesBeginnerBdsmCoachingRoute
  ServicesKinkCoachSanFranciscoRoute: typeof ServicesKinkCoachSanFranciscoRoute
  ServicesKinkEventAccompanimentRoute: typeof ServicesKinkEventAccompanimentRoute
  ServicesPolyamoryCoachingForBeginnersRoute: typeof ServicesPolyamoryCoachingForBeginnersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zines': {
      id: '/zines'
      path: '/zines'
      fullPath: '/zines'
      preLoaderRoute: typeof ZinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene-negotiator': {
      id: '/scene-negotiator'
      path: '/scene-negotiator'
      fullPath: '/scene-negotiator'
      preLoaderRoute: typeof SceneNegotiatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-party-negotiation-form': {
      id: '/play-party-negotiation-form'
      path: '/play-party-negotiation-form'
      fullPath: '/play-party-negotiation-form'
      preLoaderRoute: typeof PlayPartyNegotiationFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-party-negotiation-checklist': {
      id: '/play-party-negotiation-checklist'
      path: '/play-party-negotiation-checklist'
      fullPath: '/play-party-negotiation-checklist'
      preLoaderRoute: typeof PlayPartyNegotiationChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiate': {
      id: '/negotiate'
      path: '/negotiate'
      fullPath: '/negotiate'
      preLoaderRoute: typeof NegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zines/': {
      id: '/zines/'
      path: '/'
      fullPath: '/zines/'
      preLoaderRoute: typeof ZinesIndexRouteImport
      parentRoute: typeof ZinesRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/scene-negotiator/': {
      id: '/scene-negotiator/'
      path: '/'
      fullPath: '/scene-negotiator/'
      preLoaderRoute: typeof SceneNegotiatorIndexRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/zines/$zineSlug': {
      id: '/zines/$zineSlug'
      path: '/$zineSlug'
      fullPath: '/zines/$zineSlug'
      preLoaderRoute: typeof ZinesZineSlugRouteImport
      parentRoute: typeof ZinesRoute
    }
    '/shop/terms-of-service': {
      id: '/shop/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/shop/terms-of-service'
      preLoaderRoute: typeof ShopTermsOfServiceRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/returns-faq': {
      id: '/shop/returns-faq'
      path: '/returns-faq'
      fullPath: '/shop/returns-faq'
      preLoaderRoute: typeof ShopReturnsFaqRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/privacy-policy': {
      id: '/shop/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/shop/privacy-policy'
      preLoaderRoute: typeof ShopPrivacyPolicyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/services/polyamory-coaching-for-beginners': {
      id: '/services/polyamory-coaching-for-beginners'
      path: '/services/polyamory-coaching-for-beginners'
      fullPath: '/services/polyamory-coaching-for-beginners'
      preLoaderRoute: typeof ServicesPolyamoryCoachingForBeginnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/kink-event-accompaniment': {
      id: '/services/kink-event-accompaniment'
      path: '/services/kink-event-accompaniment'
      fullPath: '/services/kink-event-accompaniment'
      preLoaderRoute: typeof ServicesKinkEventAccompanimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/kink-coach-san-francisco': {
      id: '/services/kink-coach-san-francisco'
      path: '/services/kink-coach-san-francisco'
      fullPath: '/services/kink-coach-san-francisco'
      preLoaderRoute: typeof ServicesKinkCoachSanFranciscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/beginner-bdsm-coaching': {
      id: '/services/beginner-bdsm-coaching'
      path: '/services/beginner-bdsm-coaching'
      fullPath: '/services/beginner-bdsm-coaching'
      preLoaderRoute: typeof ServicesBeginnerBdsmCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene-negotiator/settings': {
      id: '/scene-negotiator/settings'
      path: '/settings'
      fullPath: '/scene-negotiator/settings'
      preLoaderRoute: typeof SceneNegotiatorSettingsRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/scene-negotiator/onboarding': {
      id: '/scene-negotiator/onboarding'
      path: '/onboarding'
      fullPath: '/scene-negotiator/onboarding'
      preLoaderRoute: typeof SceneNegotiatorOnboardingRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/scene-negotiator/kinks': {
      id: '/scene-negotiator/kinks'
      path: '/kinks'
      fullPath: '/scene-negotiator/kinks'
      preLoaderRoute: typeof SceneNegotiatorKinksRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/guides/preparing-for-your-first-kink-event': {
      id: '/guides/preparing-for-your-first-kink-event'
      path: '/guides/preparing-for-your-first-kink-event'
      fullPath: '/guides/preparing-for-your-first-kink-event'
      preLoaderRoute: typeof GuidesPreparingForYourFirstKinkEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/kink-red-flags-for-beginners': {
      id: '/guides/kink-red-flags-for-beginners'
      path: '/guides/kink-red-flags-for-beginners'
      fullPath: '/guides/kink-red-flags-for-beginners'
      preLoaderRoute: typeof GuidesKinkRedFlagsForBeginnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-negotiate-your-first-scene': {
      id: '/guides/how-to-negotiate-your-first-scene'
      path: '/guides/how-to-negotiate-your-first-scene'
      fullPath: '/guides/how-to-negotiate-your-first-scene'
      preLoaderRoute: typeof GuidesHowToNegotiateYourFirstSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-enter-the-kink-scene': {
      id: '/guides/how-to-enter-the-kink-scene'
      path: '/guides/how-to-enter-the-kink-scene'
      fullPath: '/guides/how-to-enter-the-kink-scene'
      preLoaderRoute: typeof GuidesHowToEnterTheKinkSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene-negotiator/sessions/': {
      id: '/scene-negotiator/sessions/'
      path: '/sessions'
      fullPath: '/scene-negotiator/sessions/'
      preLoaderRoute: typeof SceneNegotiatorSessionsIndexRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/shop/products/$productSlug': {
      id: '/shop/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/shop/products/$productSlug'
      preLoaderRoute: typeof ShopProductsProductSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/collections/$collectionSlug': {
      id: '/shop/collections/$collectionSlug'
      path: '/collections/$collectionSlug'
      fullPath: '/shop/collections/$collectionSlug'
      preLoaderRoute: typeof ShopCollectionsCollectionSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/scene-negotiator/sessions/new': {
      id: '/scene-negotiator/sessions/new'
      path: '/sessions/new'
      fullPath: '/scene-negotiator/sessions/new'
      preLoaderRoute: typeof SceneNegotiatorSessionsNewRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/scene-negotiator/scene/$token': {
      id: '/scene-negotiator/scene/$token'
      path: '/scene/$token'
      fullPath: '/scene-negotiator/scene/$token'
      preLoaderRoute: typeof SceneNegotiatorSceneTokenRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/scene-negotiator/join/$token': {
      id: '/scene-negotiator/join/$token'
      path: '/join/$token'
      fullPath: '/scene-negotiator/join/$token'
      preLoaderRoute: typeof SceneNegotiatorJoinTokenRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/scene-negotiator/sessions/$sessionId/': {
      id: '/scene-negotiator/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/scene-negotiator/sessions/$sessionId/'
      preLoaderRoute: typeof SceneNegotiatorSessionsSessionIdIndexRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/scene-negotiator/sessions/$sessionId/scene': {
      id: '/scene-negotiator/sessions/$sessionId/scene'
      path: '/sessions/$sessionId/scene'
      fullPath: '/scene-negotiator/sessions/$sessionId/scene'
      preLoaderRoute: typeof SceneNegotiatorSessionsSessionIdSceneRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/scene-negotiator/sessions/$sessionId/edit': {
      id: '/scene-negotiator/sessions/$sessionId/edit'
      path: '/sessions/$sessionId/edit'
      fullPath: '/scene-negotiator/sessions/$sessionId/edit'
      preLoaderRoute: typeof SceneNegotiatorSessionsSessionIdEditRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
    '/scene-negotiator/sessions/$sessionId/aftercare': {
      id: '/scene-negotiator/sessions/$sessionId/aftercare'
      path: '/sessions/$sessionId/aftercare'
      fullPath: '/scene-negotiator/sessions/$sessionId/aftercare'
      preLoaderRoute: typeof SceneNegotiatorSessionsSessionIdAftercareRouteImport
      parentRoute: typeof SceneNegotiatorRoute
    }
  }
}

interface SceneNegotiatorRouteChildren {
  SceneNegotiatorKinksRoute: typeof SceneNegotiatorKinksRoute
  SceneNegotiatorOnboardingRoute: typeof SceneNegotiatorOnboardingRoute
  SceneNegotiatorSettingsRoute: typeof SceneNegotiatorSettingsRoute
  SceneNegotiatorIndexRoute: typeof SceneNegotiatorIndexRoute
  SceneNegotiatorJoinTokenRoute: typeof SceneNegotiatorJoinTokenRoute
  SceneNegotiatorSceneTokenRoute: typeof SceneNegotiatorSceneTokenRoute
  SceneNegotiatorSessionsNewRoute: typeof SceneNegotiatorSessionsNewRoute
  SceneNegotiatorSessionsIndexRoute: typeof SceneNegotiatorSessionsIndexRoute
  SceneNegotiatorSessionsSessionIdAftercareRoute: typeof SceneNegotiatorSessionsSessionIdAftercareRoute
  SceneNegotiatorSessionsSessionIdEditRoute: typeof SceneNegotiatorSessionsSessionIdEditRoute
  SceneNegotiatorSessionsSessionIdSceneRoute: typeof SceneNegotiatorSessionsSessionIdSceneRoute
  SceneNegotiatorSessionsSessionIdIndexRoute: typeof SceneNegotiatorSessionsSessionIdIndexRoute
}

const SceneNegotiatorRouteChildren: SceneNegotiatorRouteChildren = {
  SceneNegotiatorKinksRoute: SceneNegotiatorKinksRoute,
  SceneNegotiatorOnboardingRoute: SceneNegotiatorOnboardingRoute,
  SceneNegotiatorSettingsRoute: SceneNegotiatorSettingsRoute,
  SceneNegotiatorIndexRoute: SceneNegotiatorIndexRoute,
  SceneNegotiatorJoinTokenRoute: SceneNegotiatorJoinTokenRoute,
  SceneNegotiatorSceneTokenRoute: SceneNegotiatorSceneTokenRoute,
  SceneNegotiatorSessionsNewRoute: SceneNegotiatorSessionsNewRoute,
  SceneNegotiatorSessionsIndexRoute: SceneNegotiatorSessionsIndexRoute,
  SceneNegotiatorSessionsSessionIdAftercareRoute:
    SceneNegotiatorSessionsSessionIdAftercareRoute,
  SceneNegotiatorSessionsSessionIdEditRoute:
    SceneNegotiatorSessionsSessionIdEditRoute,
  SceneNegotiatorSessionsSessionIdSceneRoute:
    SceneNegotiatorSessionsSessionIdSceneRoute,
  SceneNegotiatorSessionsSessionIdIndexRoute:
    SceneNegotiatorSessionsSessionIdIndexRoute,
}

const SceneNegotiatorRouteWithChildren = SceneNegotiatorRoute._addFileChildren(
  SceneNegotiatorRouteChildren,
)

interface ShopRouteChildren {
  ShopPrivacyPolicyRoute: typeof ShopPrivacyPolicyRoute
  ShopReturnsFaqRoute: typeof ShopReturnsFaqRoute
  ShopTermsOfServiceRoute: typeof ShopTermsOfServiceRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionsCollectionSlugRoute: typeof ShopCollectionsCollectionSlugRoute
  ShopProductsProductSlugRoute: typeof ShopProductsProductSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopPrivacyPolicyRoute: ShopPrivacyPolicyRoute,
  ShopReturnsFaqRoute: ShopReturnsFaqRoute,
  ShopTermsOfServiceRoute: ShopTermsOfServiceRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionsCollectionSlugRoute: ShopCollectionsCollectionSlugRoute,
  ShopProductsProductSlugRoute: ShopProductsProductSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface ZinesRouteChildren {
  ZinesZineSlugRoute: typeof ZinesZineSlugRoute
  ZinesIndexRoute: typeof ZinesIndexRoute
}

const ZinesRouteChildren: ZinesRouteChildren = {
  ZinesZineSlugRoute: ZinesZineSlugRoute,
  ZinesIndexRoute: ZinesIndexRoute,
}

const ZinesRouteWithChildren = ZinesRoute._addFileChildren(ZinesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  CoachingRoute: CoachingRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  NegotiateRoute: NegotiateRoute,
  PlayPartyNegotiationChecklistRoute: PlayPartyNegotiationChecklistRoute,
  PlayPartyNegotiationFormRoute: PlayPartyNegotiationFormRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SceneNegotiatorRoute: SceneNegotiatorRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  TermsRoute: TermsRoute,
  WorkshopsRoute: WorkshopsRoute,
  ZinesRoute: ZinesRouteWithChildren,
  GuidesHowToEnterTheKinkSceneRoute: GuidesHowToEnterTheKinkSceneRoute,
  GuidesHowToNegotiateYourFirstSceneRoute:
    GuidesHowToNegotiateYourFirstSceneRoute,
  GuidesKinkRedFlagsForBeginnersRoute: GuidesKinkRedFlagsForBeginnersRoute,
  GuidesPreparingForYourFirstKinkEventRoute:
    GuidesPreparingForYourFirstKinkEventRoute,
  ServicesBeginnerBdsmCoachingRoute: ServicesBeginnerBdsmCoachingRoute,
  ServicesKinkCoachSanFranciscoRoute: ServicesKinkCoachSanFranciscoRoute,
  ServicesKinkEventAccompanimentRoute: ServicesKinkEventAccompanimentRoute,
  ServicesPolyamoryCoachingForBeginnersRoute:
    ServicesPolyamoryCoachingForBeginnersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
