/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as KinksRouteImport } from './routes/kinks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsNewRouteImport } from './routes/sessions.new'
import { Route as SceneTokenRouteImport } from './routes/scene.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions.$sessionId.index'
import { Route as SessionsSessionIdSceneRouteImport } from './routes/sessions.$sessionId.scene'
import { Route as SessionsSessionIdEditRouteImport } from './routes/sessions.$sessionId.edit'
import { Route as SessionsSessionIdAftercareRouteImport } from './routes/sessions.$sessionId.aftercare'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const KinksRoute = KinksRouteImport.update({
  id: '/kinks',
  path: '/kinks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneTokenRoute = SceneTokenRouteImport.update({
  id: '/scene/$token',
  path: '/scene/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/sessions/$sessionId/',
  path: '/sessions/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdSceneRoute = SessionsSessionIdSceneRouteImport.update({
  id: '/sessions/$sessionId/scene',
  path: '/sessions/$sessionId/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdEditRoute = SessionsSessionIdEditRouteImport.update({
  id: '/sessions/$sessionId/edit',
  path: '/sessions/$sessionId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdAftercareRoute =
  SessionsSessionIdAftercareRouteImport.update({
    id: '/sessions/$sessionId/aftercare',
    path: '/sessions/$sessionId/aftercare',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kinks': typeof KinksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/join/$token': typeof JoinTokenRoute
  '/scene/$token': typeof SceneTokenRoute
  '/sessions/new': typeof SessionsNewRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$sessionId/aftercare': typeof SessionsSessionIdAftercareRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId/scene': typeof SessionsSessionIdSceneRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kinks': typeof KinksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/join/$token': typeof JoinTokenRoute
  '/scene/$token': typeof SceneTokenRoute
  '/sessions/new': typeof SessionsNewRoute
  '/sessions': typeof SessionsIndexRoute
  '/sessions/$sessionId/aftercare': typeof SessionsSessionIdAftercareRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId/scene': typeof SessionsSessionIdSceneRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kinks': typeof KinksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/join/$token': typeof JoinTokenRoute
  '/scene/$token': typeof SceneTokenRoute
  '/sessions/new': typeof SessionsNewRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$sessionId/aftercare': typeof SessionsSessionIdAftercareRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId/scene': typeof SessionsSessionIdSceneRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kinks'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/subscribe'
    | '/terms'
    | '/checkout/return'
    | '/join/$token'
    | '/scene/$token'
    | '/sessions/new'
    | '/sessions/'
    | '/sessions/$sessionId/aftercare'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/scene'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kinks'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/subscribe'
    | '/terms'
    | '/checkout/return'
    | '/join/$token'
    | '/scene/$token'
    | '/sessions/new'
    | '/sessions'
    | '/sessions/$sessionId/aftercare'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/scene'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/kinks'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/subscribe'
    | '/terms'
    | '/checkout/return'
    | '/join/$token'
    | '/scene/$token'
    | '/sessions/new'
    | '/sessions/'
    | '/sessions/$sessionId/aftercare'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/scene'
    | '/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  KinksRoute: typeof KinksRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SubscribeRoute: typeof SubscribeRoute
  TermsRoute: typeof TermsRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  JoinTokenRoute: typeof JoinTokenRoute
  SceneTokenRoute: typeof SceneTokenRoute
  SessionsNewRoute: typeof SessionsNewRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsSessionIdAftercareRoute: typeof SessionsSessionIdAftercareRoute
  SessionsSessionIdEditRoute: typeof SessionsSessionIdEditRoute
  SessionsSessionIdSceneRoute: typeof SessionsSessionIdSceneRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinks': {
      id: '/kinks'
      path: '/kinks'
      fullPath: '/kinks'
      preLoaderRoute: typeof KinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/$token': {
      id: '/scene/$token'
      path: '/scene/$token'
      fullPath: '/scene/$token'
      preLoaderRoute: typeof SceneTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/scene': {
      id: '/sessions/$sessionId/scene'
      path: '/sessions/$sessionId/scene'
      fullPath: '/sessions/$sessionId/scene'
      preLoaderRoute: typeof SessionsSessionIdSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/edit': {
      id: '/sessions/$sessionId/edit'
      path: '/sessions/$sessionId/edit'
      fullPath: '/sessions/$sessionId/edit'
      preLoaderRoute: typeof SessionsSessionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/aftercare': {
      id: '/sessions/$sessionId/aftercare'
      path: '/sessions/$sessionId/aftercare'
      fullPath: '/sessions/$sessionId/aftercare'
      preLoaderRoute: typeof SessionsSessionIdAftercareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  KinksRoute: KinksRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SubscribeRoute: SubscribeRoute,
  TermsRoute: TermsRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  JoinTokenRoute: JoinTokenRoute,
  SceneTokenRoute: SceneTokenRoute,
  SessionsNewRoute: SessionsNewRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsSessionIdAftercareRoute: SessionsSessionIdAftercareRoute,
  SessionsSessionIdEditRoute: SessionsSessionIdEditRoute,
  SessionsSessionIdSceneRoute: SessionsSessionIdSceneRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
